In [ ]:
name = "Chetan"
print("hi practice",name)

hi practice Chetan


In [ ]:
msg = "Hi {} practice today".format(name)
print(msg)

Hi Chetan practice today


In [ ]:
a = int(input("Enter 1st value:"))
b = int(input("Enter 2nd value:"))
sum = a + b
print(sum)

print((550*20)*12)

Enter 1st value:1
Enter 2nd value:1
2
132000


In [ ]:
str = "Python should return the investment on Upgrad"
print(str[0:4])
print(str[4:])
print(str[4:10])
print(str[-5:])
print(str[:14]*2)

Pyth
on should return the investment on Upgrad
on sho
pgrad
Python should Python should 


In [ ]:
mylist = ["lion","tiger","elephant"]
mytuple = ("dyno","preditors",10,"rhino",20,True)
mydict = {"name": "Ford",
          "model": "Mustang",
          "year": 2010}

print(mylist[2])
print(mytuple[2])
print(mydict)


elephant
10
{'name': 'Ford', 'model': 'Mustang', 'year': 2010}


In [ ]:
for i in range(10):
  print(i,end="")

0123456789

In [ ]:
avengers_team = ["Captian America","Thor","Iron Man"]
avengers_team.append("Wonder Woman")
avengers_dict = ["Super man","Spider man","He man"]
avengers_team.extend(avengers_dict)
avengers_team.remove("He man")
#avengers_team.index("Spider man")
avengers_team.insert(2,"Bat man")
#avengers_team.pop(0)
avengers_team



['Captian America',
 'Thor',
 'Bat man',
 'Iron Man',
 'Wonder Woman',
 'Super man',
 'Spider man']

In [ ]:
lang_dict = {"fr":"French","en":"English","jp":"Japanese","ge":"German","hn":"Hindi"}
ld = lang_dict
for k,v in ld.items():
  #print("{} stands for {}".format(k,v))
  print(ld[k])



French
English
Japanese
German
Hindi


In [ ]:
lk = lang_dict.keys()
lv = lang_dict.values

print("All keys","\n")
print(lk)

print("\n","All values","\n")
print(lv())

All keys 

dict_keys(['fr', 'en', 'jp', 'ge', 'hn'])

 All values 

dict_values(['French', 'English', 'Japanese', 'German', 'Hindi'])


In [ ]:
#list to string
msg = ["Strong","Cool","Annoy","Sad"]
s = ' '.join(msg)
print(s)

#string to list
name = "Radhe Shyam Tiwari"
list_name = name.split(" ")
print(list_name)

Strong Cool Annoy Sad
['Radhe', 'Shyam', 'Tiwari']


In [ ]:
#conditional stmt

def school_year_group(syear):
  if syear.is_integer():
    if syear < 6:
      print("Primary school")
    elif syear > 6 and syear <=10:
      print("Secondary school")
    elif syear > 10 and syear <=12:
      print("High school")
    else:
      print("invalid year for school")
  else:
    print("Please enter a valid number")

school_year = float(input("Enter your school year: "))
school_year_group(school_year)


Enter your school year: 5
Primary school


In [ ]:
def calc(n,operation="add"):
  if operation == "add":
    return n+n
  elif operation == "square":
    return n*n
  elif operation == "subtract":
    return n-n
  else:
    return "invaid"

my_num = int(input("Enter a number to calc: "))
op = input("Enter operation to calc: ")

print(calc(my_num,op))


Enter a number to calc: 2
Enter operation to calc: add
4


In [ ]:
# lambda is an anonymous function for quick calculation or compute
f_sqr = lambda n: n*n
f_add = lambda n,m: n+m
n1 = int(input("Enter first no: "))
n2 = int(input("Enter second no: "))
#print("Square of {} is {}".format(n1,f_sqr(n1)))
#print("Add of {} + {} = {}".format(n1,n2,f_add(n1,n2)))

for n in range(2,10):
  r = f_sqr(n)
  if r == 25:
    break
  else:
    print("Square of {} is {}".format(n,r))


Enter first no: 2
Enter second no: 3
Square of 2 is 4
Square of 3 is 9
Square of 4 is 16


In [ ]:
class Dog:
  def __init__(self):
    print("initializing constructor...")

  def bark(self):
    print("Woof Woof")

  def wiggle(self,n):
    for w in range(n):
      print("Wiggle {}".format(w))


tommy = Dog()
tommy.bark()
tommy.wiggle(2)

initializing constructor...
Woof Woof
Wiggle 0
Wiggle 1


In [ ]:
f = open("/tmp/upgrad/story.txt","w")
f.write("My Story \n")
f.write("Practising python today \n")
f.write("preparing for interviews unknown \n")
f.close()

f2 = open("/tmp/upgrad/story.txt", "r")

for l in f2.readlines():
  print(l)

f2.close()

My Story 

Practising python today 

preparing for interviews unknown 



In [ ]:
f13 = open("/tmp/upgrad/13.txt","w")

for i in range(1,11):
  f13.write("13 * {} = {} \n".format(i,13*i))

f13.close()

f =  open("/tmp/upgrad/13.txt","r")
l = f.read()
print(l)
f.close()

13 * 1 = 13 
13 * 2 = 26 
13 * 3 = 39 
13 * 4 = 52 
13 * 5 = 65 
13 * 6 = 78 
13 * 7 = 91 
13 * 8 = 104 
13 * 9 = 117 
13 * 10 = 130 



In [ ]:
import sys
import time
import numpy as np
size = 1000000

l1 = range(size)
l2 = range(size)

np1 = np.arange(size)
np2 = np.arange(size)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
end = time.time()
elapsed = round((end-start)*1000,2)
res_size = sys.getsizeof(1) * len(result)
print("Time to process size {} using list is {} milliseconds.".format(res_size,elapsed))

start = time.time()
np3 = np1 + np2
end = time.time()
elapsed = round((end - start)/1000,2)
npsize = np3.size * np3.itemsize

print("Time to process size {} using Numpy is {} milliseconds.".format(npsize,elapsed))


Time to process size 28000000 using list is 118.27 milliseconds.
Time to process size 8000000 using Numpy is 0.0 milliseconds.


In [ ]:
a = [1,2,3,4,5]
np4 = np.array(a)
print(np4)

[1 2 3 4 5]


In [ ]:
gifts = ["Pen drive","laptop","iphone","Voucher£10"]
win = np.random.choice(gifts,2,p=[0.3,0.1,0.1,0.5])
win[0]

'laptop'

In [ ]:
import numpy as np
a = np.array([(1,2,3),(4,5,6)])

a.shape
a.reshape(3,2)
a.flatten()
print(type(a))
print(a.dtype)

b = np.array([[1,2,3],[4,5,6],['a','b','c']])
print(type(b))
print(b.dtype)


<class 'numpy.ndarray'>
int64
<class 'numpy.ndarray'>
<U21


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a[:,1]) #Slicing is all rows and specific columns
print(a[1,:])  #Dicing is all columns and specific rows
print(a[:,1:3])

[2 6]
[5 6 7 8]
[[2 3]
 [6 7]]


In [ ]:
rarr = np.array([8,2,4,56,7,8,832,57,59,4,6,3])
indx = np.where(rarr>10)
print(rarr[np.where(rarr<10)])

echoice = np.where(rarr>10,'y','n')
echoice.reshape(3,4)

r = np.random.randint(1,100,25)
print(np.sort(r))

arr = np.random.randint(1,6,size=[5,4])

[8 2 4 7 8 4 6 3]
[ 3  5  6  9 14 16 17 32 34 38 43 49 54 62 65 65 66 68 72 79 87 87 90 91
 92]


In [ ]:

print(arr)
sorted_indx = arr[:,1].argsort()
arr[sorted_indx]


[[3 2 3 2]
 [2 5 5 4]
 [2 5 5 2]
 [5 5 4 4]
 [3 2 4 4]]


array([[3, 2, 3, 2],
       [3, 2, 4, 4],
       [2, 5, 5, 4],
       [2, 5, 5, 2],
       [5, 5, 4, 4]])

In [ ]:
import numpy as np

arr = np.random.randint(1,10,size=[10,5])
arr

array([[8, 3, 7, 1, 5],
       [9, 7, 4, 3, 8],
       [5, 1, 9, 2, 5],
       [6, 5, 2, 4, 3],
       [5, 3, 5, 3, 4],
       [5, 1, 8, 3, 6],
       [6, 5, 9, 5, 1],
       [2, 9, 2, 1, 4],
       [5, 5, 5, 8, 3],
       [8, 2, 8, 9, 4]])

In [ ]:
s = np.sort(arr,axis=0)
s

array([[2, 1, 2, 1, 1],
       [5, 1, 2, 1, 3],
       [5, 2, 4, 2, 3],
       [5, 3, 5, 3, 4],
       [5, 3, 5, 3, 4],
       [6, 5, 7, 3, 4],
       [6, 5, 8, 4, 5],
       [8, 5, 8, 5, 5],
       [8, 7, 9, 8, 6],
       [9, 9, 9, 9, 8]])

In [1]:
import pandas as pd
dict_l = {"en":"English","fr":"French","ge":"German","jp":"Japan"}
p = pd.Series(dict_l)
p

en    English
fr     French
ge     German
jp      Japan
dtype: object

In [25]:
team = pd.read_csv("/usr/upgrad/Team.csv",usecols=["Name"])
team

pokemon = pd.read_csv("/usr/upgrad/pokemon_data.csv",usecols=["Name"])
#pokemon.head(5)
#len(pokemon)
pokemon.dtypes
#pokemon.index
#pokemon.columns

Name    object
dtype: object

In [67]:
nba = pd.read_csv("/usr/upgrad/nba.csv")
#nba.dtypes
#nba.index
#nba.columns
nba.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      457 non-null    object 
 1   Team      457 non-null    object 
 2   Number    457 non-null    float64
 3   Position  457 non-null    object 
 4   Age       457 non-null    float64
 5   Height    457 non-null    object 
 6   Weight    457 non-null    float64
 7   College   373 non-null    object 
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB


In [68]:
nba.describe()

Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [94]:
#nba[["Name","Salary"]]
#nba.columns
#cols = ['Name','Team','Age','Salary']
#nba[cols].head(10)

#nba["Age5"] = nba.Age.add(5)
#nba["Weight in kg"] = round(nba.Weight/2.2,2)
#nba.info()

#same as sql group by position, count(*)
#nba.Position.value_counts()
#nba.tail(5)
nba.shape


(458, 11)

In [98]:
nba.dropna(how='any',inplace=True)
nba

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
6    Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
7     Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   
..             ...             ...     ...      ...   ...    ...     ...   
449    Rodney Hood       Utah Jazz     5.0       SG  23.0    6-8   206.0   
451  Chris Johnson       Utah Jazz    23.0       SF  26.0    6-6   206.0   
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   

           College     Salary  Age5  Weight in kg  
0            Texas  7730337.0  30.0         81.82  
1        Marquette  6796117.0  30.0        106.82  
3    Georgia State  1148640.0  27.0         84.09  
6              LSU  1170960.0  26.0        106.82  
7          Gonzaga  2165160.0  30.0        108.18  
..             ...        ...   ...           ...  
449           Duke  1348440.0  28.0         93.64  
451         Dayton   981348.0  31.0         93.64  
452       Kentucky  2239800.0  25.0        106.36  
453         Butler  2433333.0  31.0         92.27  
456         Kansas   947276.0  31.0        105.00  

[364 rows x 11 columns]

In [106]:
condition1 = nba.College == "Texas"
condition2 = nba.Salary > 7000000

#nba[condition1 & condition2]
nba[(nba.College == "Texas") & (nba.Salary > 7000000)]
#nba["Sal in Million"] = round(nba.Salary/1000000,2)
#nba


Name                   Team  Number Position   Age Height  \
0        Avery Bradley         Boston Celtics     0.0       PG  25.0    6-2   
179   Tristan Thompson    Cleveland Cavaliers    13.0        C  25.0    6-9   
294  LaMarcus Aldridge      San Antonio Spurs    12.0       PF  30.0   6-11   
414       Kevin Durant  Oklahoma City Thunder    35.0       SF  27.0    6-9   

     Weight College      Salary  Age5  Weight in kg  Sal in Million  
0     180.0   Texas   7730337.0  30.0         81.82            7.73  
179   238.0   Texas  14260870.0  30.0        108.18           14.26  
294   240.0   Texas  19689000.0  35.0        109.09           19.69  
414   240.0   Texas  20158622.0  32.0        109.09           20.16

In [131]:
#select name, team, position, college from nba where sal > 7m and age < 25

cols = ['Name','Team','Position','College','Salary']
#nba[cols]
#n = nba[(nba.Salary> 7000000) & (nba.Age < 25)]
#n[cols].sort_index

nba[(nba.Salary > 900000) & (nba.Salary < 990000)]

Name                    Team  Number Position   Age  \
25                Willie Reed           Brooklyn Nets    33.0       PF  26.0   
26            Thomas Robinson           Brooklyn Nets    41.0       PF  25.0   
27                 Henry Sims           Brooklyn Nets    14.0        C  26.0   
28               Donald Sloan           Brooklyn Nets    15.0       PG  28.0   
47              Isaiah Canaan      Philadelphia 76ers     0.0       PG  25.0   
57                  Ish Smith      Philadelphia 76ers     1.0       PG  27.0   
59            Hollis Thompson      Philadelphia 76ers    31.0       SG  25.0   
79                  Ian Clark   Golden State Warriors    21.0       SG  25.0   
99   Luc Richard Mbah a Moute    Los Angeles Clippers    12.0       PF  29.0   
117              Robert Sacre      Los Angeles Lakers    50.0        C  27.0   
119         Metta World Peace      Los Angeles Lakers    37.0       SF  36.0   
126              John Jenkins            Phoenix Suns    23.0       SG  25.0   
131              Ronnie Price            Phoenix Suns    14.0       PG  32.0   
136                Quincy Acy        Sacramento Kings    13.0       SF  25.0   
144                Seth Curry        Sacramento Kings    30.0       SG  25.0   
158            Justin Holiday           Chicago Bulls     7.0       SG  27.0   
170         Richard Jefferson     Cleveland Cavaliers    24.0       SF  35.0   
172               James Jones     Cleveland Cavaliers     1.0       SG  35.0   
214          Jared Cunningham         Milwaukee Bucks     9.0       SG  25.0   
240        Charlie Villanueva        Dallas Mavericks     3.0       PF  31.0   
256               Jason Terry         Houston Rockets    31.0       SG  38.0   
296               Matt Bonner       San Antonio Spurs    15.0        C  36.0   
316              Mike Muscala           Atlanta Hawks    31.0       PF  24.0   
325              Troy Daniels       Charlotte Hornets    30.0       SG  24.0   
327          Tyler Hansbrough       Charlotte Hornets    50.0       PF  30.0   
351          Hassan Whiteside              Miami Heat    21.0        C  26.0   
354            Dewayne Dedmon           Orlando Magic     3.0        C  26.0   
392               Mike Miller          Denver Nuggets     3.0       SG  36.0   
406           Tayshaun Prince  Minnesota Timberwolves    12.0       SF  36.0   
430              Allen Crabbe  Portland Trail Blazers    23.0       SG  24.0   
451             Chris Johnson               Utah Jazz    23.0       SF  26.0   
456               Jeff Withey               Utah Jazz    24.0        C  26.0   

    Height  Weight                College    Salary  Age5  Weight in kg  \
25    6-10   220.0            Saint Louis  947276.0  31.0        100.00   
26    6-10   237.0                 Kansas  981348.0  30.0        107.73   
27    6-10   248.0             Georgetown  947276.0  31.0        112.73   
28     6-3   205.0              Texas A&M  947276.0  33.0         93.18   
47     6-0   201.0           Murray State  947276.0  30.0         91.36   
57     6-0   175.0            Wake Forest  947276.0  32.0         79.55   
59     6-8   206.0             Georgetown  947276.0  30.0         93.64   
79     6-3   175.0                Belmont  947276.0  30.0         79.55   
99     6-8   230.0                   UCLA  947276.0  34.0        104.55   
117    7-0   270.0                Gonzaga  981348.0  32.0        122.73   
119    6-7   260.0             St. John's  947276.0  41.0        118.18   
126    6-4   215.0             Vanderbilt  981348.0  30.0         97.73   
131    6-2   190.0            Utah Valley  947276.0  37.0         86.36   
136    6-7   240.0                 Baylor  981348.0  30.0        109.09   
144    6-2   185.0                   Duke  947276.0  30.0         84.09   
158    6-6   185.0             Washington  947276.0  32.0         84.09   
170    6-7   233.0                Arizona  947276.0  40.0        105.91   
172    6-8   218.0             Mia